https:
  port : "9031"
  password : "![74qChRwe5du2zY32tTVtJg==]"


file:
  location: "/Customers-PRD.csv"
  
folder:
  location: "/PRD"
  
base:
  path: "C:/Users/v2cloud/AnypointStudio/studio-workspace/client-management-process-api/src/main/resources"